name: GHCR Login Test

on:
  push:
    branches:
      - main

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
