name: Deploy to Ubuntu Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/my-app:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/my-app:latest

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_NEW }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/my-app:latest
            docker stop my-app || true && docker rm my-app || true
            docker run -d --name my-app -p 80:80 ghcr.io/${{ secrets.GHCR_USERNAME }}/my-app:latest
          EOF
